blank_issues_enabled: false
contact_links:
  - name: oin the Discord Community
    url: https://discord.gg/eG34B6JVtM
    about: Have questions, ideas, or just want to connect? Join the Discord server to chat directly.
